Disable alpine-debug and release
For some reason on alpine linux llvm-3.9.1 doesn't compile, I'm seeing
errors:

  /home/pony/project/lib/llvm/src-llvm-3.9.1/lib/Support/DynamicLibrary.cpp:141:42: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
      if (!strcmp(symbolName, #SYM)) return &SYM
                                          ^
  /home/pony/project/lib/llvm/src-llvm-3.9.1/lib/Support/DynamicLibrary.cpp:148:5: note: in expansion of macro 'EXPLICIT_SYMBOL'
       EXPLICIT_SYMBOL(stderr);
       ^~~~~~~~~~~~~~~

The above was easy to fix by changing EXPLICIT_SYMBOL macro to cast
the return value. So change:
  if (!strcmp(symbolName, #SYM)) return &SYM

to:
  if (!strcmp(symbolName, #SYM)) return (void*)&SYM

But then there are other errors. So needs to be fixed.